dist: xenial
language: rust
rust: stable

env:
  - DATABASE_URL=postgres://overseer:blackmoon@localhost/deepwell

services:
  - postgresql

cache: cargo

addons:
  postgresql: '10'
  apt:
    packages:
      - postgresql-10
      - postgresql-client-10

stages:
  - format
  - clippy
  - test
  - doc

jobs:
  include:
    - stage: format
      before_script:
        - rustup component add rustfmt
      script:
        - rustfmt --edition=2018 src/lib.rs --check
        - rustfmt --edition=2018 deepwell-core/src/lib.rs --check
    - stage: clippy
      before_script:
        - rustup toolchain install nightly-2020-01-02-x86_64-unknown-linux-gnu
        - rustup component add clippy --toolchain nightly-2020-01-02-x86_64-unknown-linux-gnu
      script:
        - cargo +nightly-2020-01-02 clippy
    - stage: test
      rust:
        - stable
        - beta
        - nightly
      os:
        - linux
        - osx
        - windows
      before_script:
        - psql -c "CREATE USER overseer PASSWORD 'blackmoon';" -U postgres
        - psql -c "CREATE DATABASE deepwell OWNER overseer;" -U postgres
        - which diesel || cargo install diesel_cli --no-default-features --features postgres
      script:
        - diesel migration run
        - diesel migration redo
        - cargo build --verbose --release
        - cargo test --verbose --release -- --nocapture
        - cd deepwell-core
        - cargo build --verbose --release
        - cargo test --verbose --release -- --nocapture
    - stage: doc
      script:
        - cargo doc --verbose --release

notifications:
  email:
    on_success: change
    on_failure: always
