language: rust
rust:
  - stable
  - beta
  - nightly

os:
  - linux
  - osx
  - windows

env:
  - DATABASE_URL=postgres://overseer:blackmoon@localhost/deepwell

services:
  - postgresql

addons:
  postgresql: '10'
  apt:
    packages:
      - postgresql-10
      - postgresql-client-10

before_script:
  # Add rustfmt
  - rustup component add rustfmt
  # Add clippy
  - .travis/clippy.sh setup
  # Setup database
  - cargo install diesel_cli --no-default-features --features postgres
  - psql -c "CREATE USER overseer PASSWORD 'blackmoon';" -U postgres
  - psql -c "CREATE DATABASE deepwell OWNER overseer;" -U postgres

script:
  # Ensure code is rustfmt'd
  - .travis/banner.sh rustfmt
  - rustfmt --edition=2018 src/lib.rs --check
  # Check clippy lints
  - .travis/banner.sh clippy
  - .travis/clippy.sh check
  # Test migrations
  - diesel migration run
  - diesel migration redo
  # Run build
  - .travis/banner.sh build
  - cargo build --release
  - cargo test --release -- --nocapture
  # Build documentation
  - .travis/banner.sh docs
  - cargo doc --no-deps

jobs:
  allow_failures:
    - rust: nightly
    - os: windows
  fast_finish: true

notifications:
  email:
    on_success: change
    on_failure: always
