[package]
name = "deepwell"
description = "Database management and migrations service"
version = "0.0.1"
authors = [
    "Ammon Smith <ammon.i.smith@gmail.com>",
    "not_a_seagull <not_a_seagull048@gmail.com>",
]
edition = "2018" # this refers to the Cargo.toml

[dependencies]
askama = "0.8"
chrono = { version = "0.4", features = ["serde"] }
color-backtrace = "0.2"
diesel = { version = "1", features = ["postgres", "serde_json"] }
heck = "0.3"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
