[package]
name = "deepwell"
description = "Database management and migrations service"
version = "0.0.1"
authors = ["Ammon Smith <ammon.i.smith@gmail.com>"]
edition = "2018" # this refers to the Cargo.toml

[dependencies]
chrono = { version = "0.4", features = ["serde"] }
diesel = { version = "1", features = ["postgres", "serde_json"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
