[package]
name = "deepwell"
description = "Database management and migrations service"
version = "0.0.1"
authors = ["Ammon Smith <ammon.i.smith@gmail.com>"]
edition = "2018" # this refers to the Cargo.toml

[dependencies]
arrayvec = "0.5"
chrono = { version = "0.4", features = ["serde"] }
diesel = { version = "1", features = ["postgres", "serde_json"] }
hex = "0.4"
lazy_static = "1"
parking_lot = "0.9"
regex = "1"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
subprocess = "0.1"
thiserror = "1"
wikidot-normalize = "0.2"

[dev-dependencies]
color-backtrace = "0.2"
rand = "0.7"
tempfile = "3"
