// THIS FILE WAS AUTOGENERATED BY DEEPWELL v{{ version }}
// DO NOT EDIT - MODIFY TEMPLATE INSTEAD

type Nullable<T> = T | null;

{% for model in models %}
export interface {{ model.name }} {
  {%- for field in model.fields %}
    {% if field.has_default %}// Has default value
    {% endif %}{{ field.name }}: {% if field.is_nullable %}Nullable<{% endif -%}
      {{ field.data_type.ts_type_name() }} {%- if field.is_array %}[]{% endif -%}
    {% if field.is_nullable %}>{% endif -%}
    ;
{% endfor %}
}
{% endfor %}

// vim: set ft=jinja:
